language: php

node_js:
  - 0.12

php:
  - 5.6
  - 7.0
  - hhvm

before_script:
  - npm install
  - composer install --dev --prefer-source

before_install:
  - composer selfupdate

install: composer update --prefer-dist --no-interaction

script: ./bin/phpunit
