language: php

node_js:
  - 0.12

php:
  - 5.6
  - 7.0
  - hhvm

matrix:
  fast_finish: true
  include:
    - php: 5.6
      env: SYMFONY_VERSION=2.8.*
    - php: 5.6
      env: SYMFONY_VERSION=3.0.*
  allow_failures:
    - php: hhvm

before_install:
  - composer selfupdate
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; fi;

install:
  - npm install
  - composer update --prefer-source --no-interaction

script: ./bin/phpunit
