parameters:
  hshn.npm.bin: ~

services:
  hshn.package_manager.npm:
    public: false
    class: Hshn\NpmBundle\Npm\Npm
    arguments:
      - ~

  hshn.package_manager.yarn:
    public: false
    class: Hshn\NpmBundle\Npm\Yarn
    arguments:
      - ~

  hshn.npm.manager:
    public: false
    class: Hshn\NpmBundle\Npm\NpmManager
    arguments:
      - ~

  hshn.npm.config:
    abstract: true
    class: Hshn\NpmBundle\Npm\Configuration

  # commands
  hshn.npm.commands.abstract:
    abstract: true
    class: Hshn\NpmBundle\Command\AbstractNpmCommand
    arguments: ["@hshn.npm.manager"]

  hshn.npm.commands.install:
    parent: hshn.npm.commands.abstract
    class: Hshn\NpmBundle\Command\NpmInstallCommand
    tags: [{name: console.command}]

  hshn.npm.commands.run:
    parent: hshn.npm.commands.abstract
    class: Hshn\NpmBundle\Command\NpmRunCommand
    tags: [{name: console.command}]
