parameters:
  hshn.npm.bin: ~

services:
  hshn.npm:
    public: false
    class: Hshn\NpmBundle\Npm\Npm
    arguments: [%hshn.npm.bin%]

  hshn.npm.manager:
    public: false
    class: Hshn\NpmBundle\Npm\NpmManager
    arguments:
      - "@hshn.npm"
      - ~

  hshn.npm.config:
    abstract: true
    class: Hshn\NpmBundle\Npm\Configuration

  # commands
  hshn.npm.commands.abstract:
    abstract: true
    class: Hshn\NpmBundle\Command\AbstractNpmCommand
    arguments: ["@hshn.npm.manager"]

  hshn.npm.commands.install:
    parent: hshn.npm.commands.abstract
    class: Hshn\NpmBundle\Command\NpmInstallCommand
    tags: [{name: console.command}]
